/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cl.duoc.chocolateria.vista;

//import cl.duoc.taller1.controlador.Agregar;
//import cl.duoc.taller1.controlador.Buscar;
//import cl.duoc.taller1.controlador.Eliminar;
//import cl.duoc.taller1.modelo.Guitarra;
//import cl.duoc.taller1.modelo.Instrumento;
//import cl.duoc.taller1.modelo.Piano;
//import cl.duoc.taller1.modelo.RegistroInstrumento;
import cl.duoc.chocolateria.controlador.Controlador;
import cl.duoc.chocolateria.modelo.Chocolate;
import cl.duoc.chocolateria.modelo.Marca;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Gustavo Leiva
 */
public class VistaP extends javax.swing.JFrame {

    /**
     * Creates new form VistaP
     */
    public VistaP() {
        initComponents();
        panelAgregar.setVisible(false);
        panelListar.setVisible(false);
        panelEliminar.setVisible(false);
        
//        jComboBox1.setEnabled(false);
//        jComboBox2.setEnabled(false);
        Controlador.generar1().cargarChocolateria();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLayerdPanel = new javax.swing.JLayeredPane();
        panelAgregar = new javax.swing.JPanel();
        lblTitulo1 = new javax.swing.JLabel();
        lblTitulo2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lbl1 = new javax.swing.JLabel();
        lbl2 = new javax.swing.JLabel();
        lbl3 = new javax.swing.JLabel();
        lbl8 = new javax.swing.JLabel();
        lbl7 = new javax.swing.JLabel();
        jtx1 = new javax.swing.JTextField();
        jtx2 = new javax.swing.JTextField();
        jtx3 = new javax.swing.JTextField();
        lbl9 = new javax.swing.JLabel();
        lbEstado = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jComboBox2 = new javax.swing.JComboBox<>();
        jComboBox1 = new javax.swing.JComboBox<>();
        jRadButSi = new javax.swing.JRadioButton();
        jRadButNo = new javax.swing.JRadioButton();
        lbl4 = new javax.swing.JLabel();
        jtx4 = new javax.swing.JTextField();
        lbl5 = new javax.swing.JLabel();
        jtx5 = new javax.swing.JTextField();
        lbl51 = new javax.swing.JLabel();
        lbl41 = new javax.swing.JLabel();
        btnVolver = new javax.swing.JButton();
        lbl10 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox<>();
        panelListar = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnMostrar = new javax.swing.JButton();
        lblTitulo5 = new javax.swing.JLabel();
        lblTitulo3 = new javax.swing.JLabel();
        lblTitulo4 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        btnBuscar = new javax.swing.JButton();
        lbl12 = new javax.swing.JLabel();
        jtx6 = new javax.swing.JTextField();
        lblBusqueda = new javax.swing.JLabel();
        lblResultado = new javax.swing.JLabel();
        panelEliminar = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jtx10 = new javax.swing.JTextField();
        borrar1 = new javax.swing.JToggleButton();
        jLabel5 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu = new javax.swing.JMenu();
        jMenAgregar = new javax.swing.JMenuItem();
        jMenListar = new javax.swing.JMenuItem();
        jMenuEliminar = new javax.swing.JMenuItem();
        jMenuSalir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Biblioteca");
        setSize(panelAgregar.getPreferredSize());

        jLayerdPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLayerdPanel.setPreferredSize(new java.awt.Dimension(320, 430));

        panelAgregar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelAgregar.setPreferredSize(new java.awt.Dimension(320, 430));

        lblTitulo1.setText("Rosa Espinoza");

        lblTitulo2.setText("Chocolatería");

        lbl1.setText("Código: ");

        lbl2.setText("Nombre: ");

        lbl3.setText("Descripción: ");

        lbl8.setText("Tipo de Sabor: ");
        lbl8.setToolTipText("");

        lbl7.setText("Tipo de Chocolate: ");

        jtx1.setMaximumSize(new java.awt.Dimension(150, 20));
        jtx1.setMinimumSize(new java.awt.Dimension(150, 20));
        jtx1.setPreferredSize(new java.awt.Dimension(80, 20));

        jtx2.setMaximumSize(new java.awt.Dimension(150, 20));
        jtx2.setPreferredSize(new java.awt.Dimension(150, 20));

        jtx3.setMaximumSize(new java.awt.Dimension(150, 20));
        jtx3.setPreferredSize(new java.awt.Dimension(150, 20));

        lbl9.setText("Azucarado: ");
        lbl9.setToolTipText("");

        lbEstado.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbEstado.setText("Estado");
        lbEstado.setMaximumSize(new java.awt.Dimension(80, 14));
        lbEstado.setMinimumSize(new java.awt.Dimension(80, 14));
        lbEstado.setPreferredSize(new java.awt.Dimension(80, 20));

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        jComboBox2.setMaximumRowCount(3);
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bitter", "de Leche", "Blanco" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        jComboBox1.setMaximumRowCount(3);
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Blanco", "Negro", "Con Fruta" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadButSi);
        jRadButSi.setText("Si");
        jRadButSi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadButSiActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadButNo);
        jRadButNo.setText("No");
        jRadButNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadButNoActionPerformed(evt);
            }
        });

        lbl4.setText("Precio: ");

        jtx4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtx4ActionPerformed(evt);
            }
        });

        lbl5.setText("Cantidad: ");

        lbl51.setText("Unidades");

        lbl41.setText("pesos");

        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        lbl10.setText("Marca: ");

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nestlé", "Costa", "LaFete", "Entre Lagos" }));

        javax.swing.GroupLayout panelAgregarLayout = new javax.swing.GroupLayout(panelAgregar);
        panelAgregar.setLayout(panelAgregarLayout);
        panelAgregarLayout.setHorizontalGroup(
            panelAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAgregarLayout.createSequentialGroup()
                .addGroup(panelAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAgregarLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnGuardar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnLimpiar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnVolver)
                        .addGap(3, 3, 3))
                    .addGroup(panelAgregarLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jSeparator1))
                    .addGroup(panelAgregarLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panelAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbEstado, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSeparator2))))
                .addGap(10, 10, 10))
            .addGroup(panelAgregarLayout.createSequentialGroup()
                .addGroup(panelAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelAgregarLayout.createSequentialGroup()
                        .addGroup(panelAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(panelAgregarLayout.createSequentialGroup()
                                    .addGap(47, 47, 47)
                                    .addGroup(panelAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lbl1, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(lbl2, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(lbl3, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(lbl4, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(lbl5, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(lbl9, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(lbl10, javax.swing.GroupLayout.Alignment.TRAILING)))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAgregarLayout.createSequentialGroup()
                                    .addContainerGap()
                                    .addComponent(lbl7)))
                            .addComponent(lbl8, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(panelAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jtx1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jtx2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jtx3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(panelAgregarLayout.createSequentialGroup()
                                        .addComponent(jtx4, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lbl41)))
                                .addGroup(panelAgregarLayout.createSequentialGroup()
                                    .addComponent(jtx5, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(lbl51))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAgregarLayout.createSequentialGroup()
                                    .addComponent(jRadButSi)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jRadButNo)
                                    .addGap(77, 77, 77)))
                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelAgregarLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(panelAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTitulo2)
                            .addComponent(lblTitulo1))))
                .addContainerGap(380, Short.MAX_VALUE))
        );
        panelAgregarLayout.setVerticalGroup(
            panelAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAgregarLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lblTitulo2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTitulo1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addGroup(panelAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl1)
                    .addComponent(jtx1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl2)
                    .addComponent(jtx2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelAgregarLayout.createSequentialGroup()
                        .addComponent(lbl3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl4)
                            .addComponent(jtx4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl41))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl5)
                            .addComponent(jtx5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl51)))
                    .addComponent(jtx3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(panelAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl7)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(panelAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl8)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadButSi)
                    .addComponent(jRadButNo)
                    .addComponent(lbl9))
                .addGap(18, 18, 18)
                .addGroup(panelAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl10)
                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(lbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardar)
                    .addComponent(btnLimpiar)
                    .addComponent(btnVolver))
                .addGap(26, 26, 26))
        );

        panelListar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelListar.setPreferredSize(new java.awt.Dimension(450, 450));

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        btnMostrar.setText("Mostrar");
        btnMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarActionPerformed(evt);
            }
        });

        lblTitulo5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo5.setText("Inventario de Chocolates");

        lblTitulo3.setText("Chocolatería");

        lblTitulo4.setText("Rosa Espinoza");

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        lbl12.setText("Código: ");
        lbl12.setToolTipText("");

        jtx6.setToolTipText("");

        lblBusqueda.setText("Resultado búsqueda: ");

        lblResultado.setText("Estado");

        javax.swing.GroupLayout panelListarLayout = new javax.swing.GroupLayout(panelListar);
        panelListar.setLayout(panelListarLayout);
        panelListarLayout.setHorizontalGroup(
            panelListarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelListarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelListarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 514, Short.MAX_VALUE)
                    .addComponent(lblTitulo5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator3)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelListarLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(panelListarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelListarLayout.createSequentialGroup()
                                .addComponent(lbl12)
                                .addGap(18, 18, 18)
                                .addComponent(jtx6, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnBuscar))
                        .addGap(18, 18, 18)
                        .addComponent(btnMostrar))
                    .addComponent(lblResultado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelListarLayout.createSequentialGroup()
                        .addGroup(panelListarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTitulo3)
                            .addComponent(lblTitulo4)
                            .addComponent(lblBusqueda))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelListarLayout.setVerticalGroup(
            panelListarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelListarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTitulo4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addComponent(lblTitulo5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                .addComponent(lblBusqueda)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblResultado)
                .addGap(20, 20, 20)
                .addGroup(panelListarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl12)
                    .addComponent(jtx6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(panelListarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMostrar)
                    .addComponent(btnBuscar))
                .addContainerGap())
        );

        panelEliminar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel4.setText("Código: ");

        borrar1.setText("Borrar");
        borrar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrar1ActionPerformed(evt);
            }
        });

        jLabel5.setText("Estado");

        javax.swing.GroupLayout panelEliminarLayout = new javax.swing.GroupLayout(panelEliminar);
        panelEliminar.setLayout(panelEliminarLayout);
        panelEliminarLayout.setHorizontalGroup(
            panelEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEliminarLayout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addGroup(panelEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addGroup(panelEliminarLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(jtx10, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(borrar1)))
                .addContainerGap(276, Short.MAX_VALUE))
        );
        panelEliminarLayout.setVerticalGroup(
            panelEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEliminarLayout.createSequentialGroup()
                .addGap(170, 170, 170)
                .addGroup(panelEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jtx10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(borrar1))
                .addGap(31, 31, 31)
                .addComponent(jLabel5)
                .addContainerGap(211, Short.MAX_VALUE))
        );

        jLayerdPanel.setLayer(panelAgregar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayerdPanel.setLayer(panelListar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayerdPanel.setLayer(panelEliminar, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayerdPanelLayout = new javax.swing.GroupLayout(jLayerdPanel);
        jLayerdPanel.setLayout(jLayerdPanelLayout);
        jLayerdPanelLayout.setHorizontalGroup(
            jLayerdPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelListar, javax.swing.GroupLayout.DEFAULT_SIZE, 536, Short.MAX_VALUE)
            .addGroup(jLayerdPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panelAgregar, javax.swing.GroupLayout.DEFAULT_SIZE, 536, Short.MAX_VALUE))
            .addGroup(jLayerdPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panelEliminar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jLayerdPanelLayout.setVerticalGroup(
            jLayerdPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelListar, javax.swing.GroupLayout.DEFAULT_SIZE, 451, Short.MAX_VALUE)
            .addGroup(jLayerdPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panelAgregar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 451, Short.MAX_VALUE))
            .addGroup(jLayerdPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panelEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jMenu.setText("Procesos");

        jMenAgregar.setText("Agregar");
        jMenAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenAgregarActionPerformed(evt);
            }
        });
        jMenu.add(jMenAgregar);

        jMenListar.setText("Listar");
        jMenListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenListarActionPerformed(evt);
            }
        });
        jMenu.add(jMenListar);

        jMenuEliminar.setText("Eliminar");
        jMenuEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuEliminarActionPerformed(evt);
            }
        });
        jMenu.add(jMenuEliminar);

        jMenuSalir.setText("Salir");
        jMenuSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuSalirActionPerformed(evt);
            }
        });
        jMenu.add(jMenuSalir);

        jMenuBar1.add(jMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayerdPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 538, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayerdPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 453, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuSalirActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jMenuSalirActionPerformed

    private void jMenAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenAgregarActionPerformed
        // TODO add your handling code here:
        panelAgregar.setVisible(true);
        panelListar.setVisible(false);
        panelEliminar.setVisible(false);
        lbEstado.setText("Estado");
    }//GEN-LAST:event_jMenAgregarActionPerformed

    private void jMenListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenListarActionPerformed
        // TODO add your handling code here:
        panelAgregar.setVisible(false);
        panelListar.setVisible(true);
        panelEliminar.setVisible(false);
    }//GEN-LAST:event_jMenListarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        // TODO add your handling code here:
        jtx1.setText("");
        jtx2.setText("");
        jtx3.setText("");
        jtx4.setText("");
        jtx5.setText("");
        
        
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        try{
            Integer codigo = Integer.parseInt(jtx1.getText());
            String nombre =jtx2.getText();
            String descripcion =jtx3.getText();
            Integer precio = Integer.parseInt(jtx4.getText());
            Integer cantidad = Integer.parseInt(jtx5.getText());
            
            String tipochocolate="";
            String tiposabor="";
            String azucarado="";
            String marca="";
            Integer codigomarca=0;
            
            if(jRadButSi.isSelected()){
                azucarado = "Si";
            }else{
                azucarado = "No";
            }
            
            switch(jComboBox1.getSelectedIndex()){
                    case 0:
                        tipochocolate = "Blanco";
                        break;

                    case 1:
                        tipochocolate = "Negro";
                        break;
                    case 2:
                        tipochocolate = "con Fruta";
                        break; 
            }
            switch(jComboBox2.getSelectedIndex()){
                    case 0:
                        tiposabor = "Bitter";
                        break;

                    case 1:
                        tiposabor = "de Leche";
                        break;
                    case 2:
                        tiposabor = "Blanco";
                        break;                        
            
            }
            switch(jComboBox3.getSelectedIndex()){
                    case 0:
                        codigomarca = 100;
                        marca=jComboBox3.getItemAt(0);
                        break;

                    case 1:
                        codigomarca = 101;
                        marca=jComboBox3.getItemAt(1);
                        break;
                    case 2:
                        codigomarca = 102;
                        marca=jComboBox3.getItemAt(2);
                        break; 
                    case 3:
                        codigomarca = 103;
                        marca=jComboBox3.getItemAt(3);
                        break;                        
            
            }            
                        
            Chocolate a1 = new Chocolate( codigo,  nombre,  descripcion, 
                     precio,  cantidad,  tipochocolate,  tiposabor, 
                     marca,  azucarado,  codigomarca);
            
            if(Controlador.generar1().agregarChocolate(a1)){
               lbEstado.setText("Chocolate agregado");
            }else{
                lbEstado.setText("Chocolate no se pudo agregar");
            }
        }catch(NumberFormatException ex){
            System.out.println("error de campos");
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarActionPerformed
        // TODO add your handling code here:
        
        DefaultTableModel InvActual = new DefaultTableModel();
        jTable1.setModel(InvActual);
        
        InvActual.addColumn("Código");
        InvActual.addColumn("Nombre");
        InvActual.addColumn("Descripcion");
        InvActual.addColumn("Precio");
        InvActual.addColumn("Cantidad");
        InvActual.addColumn("Chocolate");
        InvActual.addColumn("Sabor");
        InvActual.addColumn("Azucarado");
        InvActual.addColumn("Marca");
        
        Object[] fila = new Object[9];
        //lblestado.setText("Correcto");
        ArrayList <Chocolate> auxil = Controlador.getChocs();
        
        for(int x =0; x < auxil.size(); ++x){
            fila[0] = auxil.get(x).getCodigoChoc();
            fila[1] = auxil.get(x).getNombre();
            fila[2] = auxil.get(x).getDescripcion();
            fila[3] = auxil.get(x).getPrecio();
            fila[4] = auxil.get(x).getCantidad();
            fila[5] = auxil.get(x).getTipoChoc();
            fila[6] = auxil.get(x).getTipoSabor();
            fila[7] = auxil.get(x).getAzucar(); 
            fila[8] = auxil.get(x).getMarca();
              
            InvActual.addRow(fila);
        }
    }//GEN-LAST:event_btnMostrarActionPerformed

    private void jMenuEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuEliminarActionPerformed
        // TODO add your handling code here:
        panelAgregar.setVisible(false);
        panelListar.setVisible(false);
        panelEliminar.setVisible(true);
        jLabel5.setText("Estado");
    }//GEN-LAST:event_jMenuEliminarActionPerformed

    private void jRadButSiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadButSiActionPerformed
        // TODO add your handling code here:
//        if(jRadButSi.isSelected()){
//            jComboBox2.setEnabled(true);
//            jComboBox1.setEnabled(false);
//        }
    }//GEN-LAST:event_jRadButSiActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jRadButNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadButNoActionPerformed
        // TODO add your handling code here:
//        if(jRadButNo.isSelected()){
//            jComboBox2.setEnabled(false);
//            jComboBox1.setEnabled(true);
//        }
    }//GEN-LAST:event_jRadButNoActionPerformed

    private void borrar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrar1ActionPerformed
        // TODO add your handling code here:
//        try{
//            int codigo =Integer.parseInt(jtx10.getText());
//            Eliminar delete = new Eliminar();
//            
//            if(delete.eliminarInstrumento(codigo)){
//                jLabel5.setText("Instrumento borrado con éxito");
//            }else{
//                jLabel5.setText("Error");
//            }
//        }catch(NumberFormatException eev){
//            
//        }
        
    }//GEN-LAST:event_borrar1ActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
//        try{
//        Buscar instr =new Buscar();
//        int codigo = Integer.parseInt(jtx6.getText());
//        Instrumento auxili =instr.buscarInstrumento(codigo);
//        
//        DefaultTableModel buscar = new DefaultTableModel();
//        jTable1.setModel(buscar);
//        
//        buscar.addColumn("Código");
//        buscar.addColumn("Nombre");
//        buscar.addColumn("Stock");
//        buscar.addColumn("Instrumento");
//        buscar.addColumn("Tipo");
//        
//        Object[] fila = new Object[5];
//        
//        fila[0] = auxili.getCodigo(); 
//        fila[1] = auxili.getNombre();
//        fila[2] = auxili.getStock();
//            
//        if (auxili instanceof Guitarra){
//               fila[3] = "Guitarra";
//               fila[4] = ((Guitarra)auxili).getTipo();                        
//        }
//        if (auxili instanceof Piano){
//               fila[3] = "Piano";
//               fila[4] = ((Piano)auxili).getTipo();                   
//        }
//        buscar.addRow(fila);
//                 
//        }catch(NumberFormatException eev){
//        
//        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        // TODO add your handling code here:
        panelAgregar.setVisible(false);
        jtx1.setText("");
        jtx2.setText("");
        jtx3.setText("");
        jtx4.setText("");
        jtx5.setText("");
    }//GEN-LAST:event_btnVolverActionPerformed

    private void jtx4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtx4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtx4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaP().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton borrar1;
    public javax.swing.JButton btnBuscar;
    public javax.swing.JButton btnGuardar;
    public javax.swing.JButton btnLimpiar;
    public javax.swing.JButton btnMostrar;
    private javax.swing.JButton btnVolver;
    public javax.swing.ButtonGroup buttonGroup1;
    public javax.swing.JComboBox<String> jComboBox1;
    public javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLayeredPane jLayerdPanel;
    public javax.swing.JMenuItem jMenAgregar;
    public javax.swing.JMenuItem jMenListar;
    private javax.swing.JMenu jMenu;
    private javax.swing.JMenuBar jMenuBar1;
    public javax.swing.JMenuItem jMenuEliminar;
    public javax.swing.JMenuItem jMenuSalir;
    public javax.swing.JRadioButton jRadButNo;
    public javax.swing.JRadioButton jRadButSi;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    public javax.swing.JTable jTable1;
    public javax.swing.JTextField jtx1;
    private javax.swing.JTextField jtx10;
    public javax.swing.JTextField jtx2;
    public javax.swing.JTextField jtx3;
    private javax.swing.JTextField jtx4;
    private javax.swing.JTextField jtx5;
    public javax.swing.JTextField jtx6;
    public javax.swing.JLabel lbEstado;
    private javax.swing.JLabel lbl1;
    private javax.swing.JLabel lbl10;
    private javax.swing.JLabel lbl12;
    private javax.swing.JLabel lbl2;
    private javax.swing.JLabel lbl3;
    private javax.swing.JLabel lbl4;
    private javax.swing.JLabel lbl41;
    private javax.swing.JLabel lbl5;
    private javax.swing.JLabel lbl51;
    private javax.swing.JLabel lbl7;
    private javax.swing.JLabel lbl8;
    private javax.swing.JLabel lbl9;
    private javax.swing.JLabel lblBusqueda;
    public javax.swing.JLabel lblResultado;
    private javax.swing.JLabel lblTitulo1;
    private javax.swing.JLabel lblTitulo2;
    private javax.swing.JLabel lblTitulo3;
    private javax.swing.JLabel lblTitulo4;
    private javax.swing.JLabel lblTitulo5;
    public javax.swing.JPanel panelAgregar;
    public javax.swing.JPanel panelEliminar;
    public javax.swing.JPanel panelListar;
    // End of variables declaration//GEN-END:variables
}
